# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Sun Lab
tagline:             'on genomic ITH'
description:         'Ruping Sun <br> Assistant Professor <br> Advanced Cancer Genomics and Bioinformatics <br> <a href="https://med.umn.edu/bio/lab-med-and-pathology-faculty/ruping-sun" target="_blank">Department of Laboratory Medicine and Pathology</a> <br> Member of <a href="https://www.cancer.umn.edu/" target="_blank"> Masonic Cancer Center </a> <br> University of Minnesota <br> <a href="http://twitter.com/Sun_Ruping" target="_blank">@Sun_Ruping</a> <br> <a href="https://scholar.google.de/citations?user=bRpxn-oAAAAJ&hl=en" target="_blank">Google Scholar</a> <br> ruping at umn dot edu <br>'

url:                 http://ruping.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0

gems:                [jekyll-paginate]
paginate_path:       "page:num"
